### ISSUE TITLE
Twitter Embed is not styling

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#12] opened 2020-06-15 23:32 UTC
The Twitter embed in the [FAQ](https://pr-5-lfph.pantheonsite.io/join/faq/#is-open-source-less-secure) page is not picking up its styling. However copy and paste that block in to another page and [it works perfectly](https://pr-5-lfph.pantheonsite.io/about/advisors/). 

This may be related to a similar issue with [CNCF posts](https://github.com/cncf/cncf.io/issues/141).

**Comment by cjyabraham** [comment] 2020-06-18 02:57
- For some reason this is not getting added to the page:
`<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

- When I either remove all tab container blocks from the page or change the page template to "Default", it works

**Comment by cjyabraham** [comment] 2020-06-18 03:37
I've checked in a workaround that makes sure widgets.js is inserted when there is a twitter block.  This means that in some situations there are two widgets.js script tags (not sure if that's bad).  I couldn't figure out the root cause of this.  I checked and the latest Gutenberg Plugin behaves the same.

If you're ok with this solution we should replicate [in CNCF](https://github.com/cncf/cncf.io/issues/141).

**Comment by cjyabraham** [comment] 2020-06-18 04:19
I ended up changing the priority of the tab container filter so that it runs prior to the filter for the twitter object.  We are calling `wp_kses_post` to sanitize the content in our filter and it strips out the twitter `<script>` tag when called after.

**Closed as completed by cjyabraham** 2020-06-18 04:19 UTC

**Comment by cjyabraham** [comment] 2020-06-18 04:40
[I ported this change to CNCF](https://github.com/cncf/cncf.io/commit/fe3be880ff0d64986ee2e61abfe5f2ddaa58c0df)

**Comment by thetwopct** [comment] 2020-06-18 10:05
Ah of course! Great work.
